address = "0.0.0.0:8081"
queue_size = 5
environment = "development"
messages_to_inject = ["freeside", "milliways", "GNU TERRY PRATCHETT"]

[timing]
show_character_for = 5
pause_between_characters_for = 2
pause_between_messages_for = 10
inject_message_if_no_next_message_after_pausing_between_messages_for = 5
